### ISSUE TITLE
Android Build Failed

### ISSUE THREAD

**Issue by tyler-elric** [Wikitude/wikitude-cordova-plugin#80]
I'm using Telerik's App Builder platform, and I've imported the wikitude cordova plugin. When I try to build the app, I get these errors:

```
	Error: [javac] /tmp/builds/1bgz0SqILVO7B726PT/app/src/com/wikitude/phonegap/WikitudePlugin.java:756: error: cannot find symbol
	Error: [javac] /tmp/builds/1bgz0SqILVO7B726PT/app/src/com/wikitude/phonegap/WikitudePlugin.java:771: error: method handleResume in class CordovaWebView cannot be applied to given types;
	Error: /home/builder/BpcTooling/BuildScripts/node_build/node_modules/child-process-promise/node_modules/q/q.js:126
                    throw e;
```

I'm not quite sure what to do about this.

**Comment by simonfriesenbichler** [comment]
Hi Tyler,

please check which Cordova version Telerik is using. Our current master will only work with the latest Cordova version (5.0). If Telerik is still using 4.x please use tag v4.1.0-3.0.1, when you add the plugin with Cordova you can specify a specific tag using following notation: https://github.com/Wikitude/wikitude-cordova-plugin#v4.1.0-3.0.1

Thank you and best regards,
Simon

**Comment by tyler-elric** [comment]
It looks like we're using Cordova 3.7.0 and the version you specified for version 4.x, I'll look into using a more recent version of Cordova, although the highest it allows is 3.8 and it's specified as "Experimental". Thank you for the information though, it's comforting to know I'm not insane.

**Comment by simonfriesenbichler** [comment]
Are you sure it's Cordova version 3.7.0 and not Android Cordova 3.7.0? If it's Android Cordova 3.7 then it was the last version before Android Cordova 4.0 which comes with Cordova 5.0, and then it should work with the older version of our plugin.

Best regards,
Simon
